typography_spectrum: 0.2998743529897183
color:
  brandColors:
    - '#4eaeac'
    - '#ffffff'
    - '#471d2b'
    - '#f97862'
    - '#facc38'
  brandStrength: 0.539935118984431
  lightness: 0.4280351437628269
  saturation: 0.5625
  rhythmicContrast: 0.5651025490369648
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.591523889452219
analytics:
  google: UA-76369834-1
  facebook: null
  twitter: null
author:
  name: Tyler Cole
  email: trylobot@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf4e530e-e2b0-4165-956a-33f08fe848d8.png
name: Trylobot Reviews Games
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Gaming as an Adult (About Me)
    id: 00d6b1c9-f61e-4f3a-b712-d11fed45719b
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dde1a046-2979-41c5-b069-bddfb07cd150.png
title: Trylobot Reviews Games
description: TL;DR Reviews for People who are Sick of Lengthy YouTube Reviews
purpose: []
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7434f74c-4e2c-42c7-8356-0855c45370a8.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7434f74c-4e2c-42c7-8356-0855c45370a8.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://thegrid.ai/trylobot/'
