name: GreyBush
favicon: null
layout_spectrum: 0.33984
typography_spectrum: 0.55757
title: Grey Bush — Seasoned Independent Videogame Reviewer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76369834-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4eaeac'
    - '#ffffff'
    - '#471d2b'
    - '#f97862'
    - '#facc38'
  brandStrength: 0.539935118984431
  lightness: 0.4280351437628269
  saturation: 0.5625
  rhythmicContrast: 0.5651025490369648
purpose: []
