name: GreyBush
favicon: null
layout_spectrum: 0.75044
typography_spectrum: 0.73858
title: Grey Bush — Videogame Reviewer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4eaeac'
    - '#ffffff'
    - '#471d2b'
    - '#f97862'
    - '#facc38'
  brandStrength: 0.539935118984431
  lightness: 0.4280351437628269
  saturation: 0.43844268936663866
  rhythmicContrast: 0.5651025490369648
purpose: []
