typography_spectrum: 0.38189
color:
  brandColors:
    - '#4eaeac'
    - '#ffffff'
    - '#471d2b'
    - '#f97862'
    - '#facc38'
  brandStrength: 0.539935118984431
  lightness: 0.4280351437628269
  saturation: 0.5625
  rhythmicContrast: 0.5651025490369648
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1664381844457239
analytics:
  google: UA-76369834-1
  facebook: null
  twitter: null
author:
  name: Tyler Cole
  email: trylobot@gmail.com
name: GreyBush
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Grey Bush — Seasoned Independent Videogame Reviewer
purpose: []
